-- megafunction wizard: %8B10B Encoder-Decoder v13.0%
-- GENERATION: XML

-- ============================================================
-- Megafunction Name(s):
-- 			kamal_lab1_3to8DecoderLPM_dec8b10b
-- ============================================================
-- Generated by 8B10B Encoder-Decoder 13.0 [Altera, IP Toolbench 1.3.0 Build 232]
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
-- ************************************************************
-- Copyright (C) 1991-2019 Altera Corporation
-- Any megafunction design, and related net list (encrypted or decrypted),
-- support information, device programming or simulation file, and any other
-- associated documentation or information provided by Altera or a partner
-- under Altera's Megafunction Partnership Program may be used only to
-- program PLD devices (but not masked PLD devices) from Altera.  Any other
-- use of such megafunction design, net list, support information, device
-- programming or simulation file, or any other related documentation or
-- information is prohibited for any other purpose, including, but not
-- limited to modification, reverse engineering, de-compiling, or use with
-- any other silicon devices, unless such use is explicitly licensed under
-- a separate agreement with Altera or a megafunction partner.  Title to
-- the intellectual property, including patents, copyrights, trademarks,
-- trade secrets, or maskworks, embodied in any such megafunction design,
-- net list, support information, device programming or simulation file, or
-- any other related documentation or information provided by Altera or a
-- megafunction partner, remains with Altera, the megafunction partner, or
-- their respective licensors.  No other licenses, including any licenses
-- needed under any third party's intellectual property, are provided herein.

library IEEE;
use IEEE.std_logic_1164.all;

ENTITY kamal_lab1_3to8DecoderLPM IS
	PORT (
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		idle_del	: IN STD_LOGIC;
		ena	: IN STD_LOGIC;
		datain	: IN STD_LOGIC_VECTOR (9 DOWNTO 0);
		rdforce	: IN STD_LOGIC;
		rdin	: IN STD_LOGIC;
		valid	: OUT STD_LOGIC;
		dataout	: OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
		kout	: OUT STD_LOGIC;
		kerr	: OUT STD_LOGIC;
		rdcascade	: OUT STD_LOGIC;
		rdout	: OUT STD_LOGIC;
		rderr	: OUT STD_LOGIC
	);
END kamal_lab1_3to8DecoderLPM;

ARCHITECTURE SYN OF kamal_lab1_3to8DecoderLPM IS


	COMPONENT kamal_lab1_3to8DecoderLPM_dec8b10b
	PORT (
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		idle_del	: IN STD_LOGIC;
		ena	: IN STD_LOGIC;
		datain	: IN STD_LOGIC_VECTOR (9 DOWNTO 0);
		rdforce	: IN STD_LOGIC;
		rdin	: IN STD_LOGIC;
		valid	: OUT STD_LOGIC;
		dataout	: OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
		kout	: OUT STD_LOGIC;
		kerr	: OUT STD_LOGIC;
		rdcascade	: OUT STD_LOGIC;
		rdout	: OUT STD_LOGIC;
		rderr	: OUT STD_LOGIC
	);

	END COMPONENT;

BEGIN

	kamal_lab1_3to8DecoderLPM_dec8b10b_inst : kamal_lab1_3to8DecoderLPM_dec8b10b
	PORT MAP (
		clk  =>  clk,
		reset_n  =>  reset_n,
		idle_del  =>  idle_del,
		ena  =>  ena,
		datain  =>  datain,
		rdforce  =>  rdforce,
		rdin  =>  rdin,
		valid  =>  valid,
		dataout  =>  dataout,
		kout  =>  kout,
		kerr  =>  kerr,
		rdcascade  =>  rdcascade,
		rdout  =>  rdout,
		rderr  =>  rderr
	);


END SYN;

